___

<a href="https://lms.clarusway.com/course/view.php?id=37"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/3-DVwPY/DVwPy_S06_Capstone_Project%20(Bike%20Store%20Sharing).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="100" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DVwPY_S6/6-DVwPy%20Capstone%20%28Bike%20Store%20Sharing%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="130" height="200" title="Open and Execute in nbviewer"></a><br/>
___

<a href="https://clarusway.com/"><img align="center" src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" alt="CLRSWY" width="450" height="200" title="Welcome to Place Where You can Reinvent Yourself"></a><br/>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE

import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [3]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]
new_list = np.array(my_list)

### 3. Generate an array of 5x5 with zeros. 

In [6]:
# YOUR CODE IS HERE

np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [7]:
# YOUR CODE IS HERE
np.ones((4, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [9]:
# YOUR CODE IS HERE

np.ones((4, 4), dtype = int)*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
# YOUR CODE IS HERE

np.full((4, 4), 7)

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [10]:
# YOUR CODE IS HERE

a = np.arange(2,17,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [15]:
# YOUR CODE IS HERE
b = np.arange(0, 25).reshape(5, 5)
b



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [17]:
# YOUR CODE IS HERE

np.linspace(0, 25, endpoint = False)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5])

### 10. Create randomly 5 numbers with numpy.

In [18]:
# YOUR CODE IS HERE

np.random.rand(5)

array([0.57887944, 0.16049131, 0.07541864, 0.85462193, 0.39026387])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [19]:
# YOUR CODE IS HERE

np.random.randn(5,5)

array([[-1.16686407, -1.68461572,  0.77255003, -1.48475614, -0.94553811],
       [ 1.77557106, -0.64055221,  0.84481939,  0.09507987,  0.16372372],
       [ 0.04508053, -2.07479816,  1.23706896,  0.30749864,  0.80827924],
       [ 0.28518711, -0.35437083,  0.10684326, -0.56654938, -0.95083276],
       [ 0.38150918,  0.05269331,  0.19049415,  1.18098206, -0.86057617]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [21]:
# YOUR CODE IS HERE

np.random.randint(20, 50, size = (3, 4))

array([[34, 32, 30, 49],
       [35, 45, 44, 26],
       [37, 36, 24, 37]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [29]:
# YOUR CODE IS HERE

ranarr = np.random.randint(10, 70, size = 48)
ranarr

array([27, 52, 25, 68, 19, 42, 66, 28, 10, 61, 62, 25, 55, 48, 36, 16, 42,
       39, 12, 29, 39, 35, 16, 23, 19, 52, 62, 13, 25, 28, 64, 54, 25, 13,
       69, 27, 16, 46, 51, 35, 35, 19, 65, 51, 53, 24, 47, 45])

In [33]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr.reshape(6, 8)

array([[27, 52, 25, 68, 19, 42, 66, 28],
       [10, 61, 62, 25, 55, 48, 36, 16],
       [42, 39, 12, 29, 39, 35, 16, 23],
       [19, 52, 62, 13, 25, 28, 64, 54],
       [25, 13, 69, 27, 16, 46, 51, 35],
       [35, 19, 65, 51, 53, 24, 47, 45]])

In [34]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6, -1)

array([[27, 52, 25, 68, 19, 42, 66, 28],
       [10, 61, 62, 25, 55, 48, 36, 16],
       [42, 39, 12, 29, 39, 35, 16, 23],
       [19, 52, 62, 13, 25, 28, 64, 54],
       [25, 13, 69, 27, 16, 46, 51, 35],
       [35, 19, 65, 51, 53, 24, 47, 45]])

In [35]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(-1, 8)

array([[27, 52, 25, 68, 19, 42, 66, 28],
       [10, 61, 62, 25, 55, 48, 36, 16],
       [42, 39, 12, 29, 39, 35, 16, 23],
       [19, 52, 62, 13, 25, 28, 64, 54],
       [25, 13, 69, 27, 16, 46, 51, 35],
       [35, 19, 65, 51, 53, 24, 47, 45]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [61]:
# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [44]:
# YOUR CODE IS HERE 
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [48]:
# YOUR CODE IS HERE 
mat[0:4, 0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [50]:
# YOUR CODE IS HERE 
mat[1, 0:4:2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [115]:
# YOUR CODE IS HERE 
mat[0:4, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [132]:
# YOUR CODE IS HERE 
np.array([mat[1,0], mat[3,2]])

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [95]:
# YOUR CODE IS HERE 
mat[1::2, 0::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [96]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
 
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [97]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [98]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [100]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

a = mat[mat<10] + mat[mat>12]
a

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [108]:
# YOUR CODE IS HERE 
np.std(a)

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [109]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [139]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [143]:
# YOUR CODE IS HERE 
new = mat[0:4, 1]
new
np.sum(new, axis = 0)

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [144]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
mat = np.arange(1,17).reshape(4,4)
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [153]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

x = mat[0:4, 2].reshape(4,1)
x

array([[ 3],
       [ 7],
       [11],
       [15]])

In [154]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

y = mat[2, 0:4]
y

array([ 9, 10, 11, 12])

In [160]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 
np.median(x), np.median(y)


(9.0, 10.5)

In [161]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

np.mean(x), np.mean(y)

(9.0, 10.5)

In [162]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

np.std(x), np.std(y)

(4.47213595499958, 1.118033988749895)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [24]:
# YOUR CODE IS HERE 

import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [33]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 

table = pd.read_csv("Salaries.csv") # dosyayı asla okutamadım.

FileNotFoundError: [Errno 2] No such file or directory: 'Salaries.csv'

In [27]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 

Salaries.head()

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [28]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

Salaries.sample()

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 



### Print out max and avg values in the column of "Totalpay".

In [ ]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 



In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 



### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 



### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 



### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 



### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 



### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 



### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 



### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION FOR THIS QUESTION!

# YOUR CODE IS HERE 



### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [ ]:
# YOUR CODE IS HERE 



Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________